### ISSUE TITLE
can't get it to work with Java 11 or 15

### ISSUE THREAD

**Issue by Ed42** [ebean-orm-examples/example-gradle-java#3]
Trying to get this example to work with Java 11, also tried Java 15. Have also tried with latest ebean 12.6.4.

[build.log](https://github.com/ebean-orm-examples/example-gradle-java/files/5758386/build.log)

[build.gradle.diff.txt](https://github.com/ebean-orm-examples/example-gradle-java/files/5758387/build.gradle.diff.txt)

**Comment by rbygrave** [comment]
Hi Ed, I'm off on holiday at the moment.  Remind me around the 19th.

**Comment by rbygrave** [comment]
also note there is a more up to date gradle example at https://github.com/ebean-orm/examples/tree/master/basic-gradle-java
... but yeah, I'll update this example project.

**Comment by rbygrave** [comment]
Updated to use Java 11 (will also support Java 15).  Re-open this if it isn't working for you.  Cheers, Rob.
